"""Provider protocol module.

Failure-mode fixture R6 (lazy-label package-init hop): this module lives
inside a nested subpackage ``tts.providers``.  When another file does a
function-level import like::

    from tts.providers.protocol import (
        ProviderError as PErr,
    )

StackGraphs may create Import edges to both ``protocol.py`` (the final
target) AND to intermediate ``__init__.py`` files traversed during
package resolution.  The lazy reclassifier must propagate the ImportLazy
label to ALL edges generated by that deferred import, including hops.
"""


class ProviderError(Exception):
    """Base error for provider operations."""

    def __init__(self, message: str, code: int = 0):
        super().__init__(message)
        self.code = code


class ProviderTimeoutError(ProviderError):
    """Timeout during provider call."""
    pass
